package cn.ralken.android.server.util;

public enum ConfigType {
	LENGTH_UNIT, WEIGHT_UNIT, TEMP_UNIT, TIME_FREQ, INDOOR_FREQ, CITY, TIME_ZONE, OUTDOOR_FREQ, TIME_SYNC_FREQ, BASE_TIME, WEATHER_PATTERN;
}
